/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const { versionSelector, versionCrumb } = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");
const restApiVersions = require("./docs/rest-api/versions.json");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    mainSidebar: [
        {
            type: "category",
            label: "Documentation",
            link: {
                type: "generated-index",
                title: "Docs",
                description: "Learn more about the Novorender's open source APIs",
            },
            collapsed: false,
            items: [
                {
                    type: "category",
                    label: "WebGL API",
                    link: {
                        type: "doc",
                        id: "webgl-api/index",
                    },
                    items: [{ type: "autogenerated", dirName: "webgl-api" }],
                },
                {
                    type: "category",
                    label: "Data JS API",
                    link: {
                        type: "doc",
                        id: "data-js-api/index",
                    },
                    items: [{ type: "autogenerated", dirName: "data-js-api" }],
                },
                {
                    type: "category",
                    label: "Measure API",
                    link: {
                        type: "doc",
                        id: "measure-api/index",
                    },
                    items: [{ type: "autogenerated", dirName: "measure-api" }],
                },
                {
                    type: "category",
                    label: "Tutorials",
                    link: {
                        type: "generated-index",
                        title: "Tutorials",
                        description: "Learn more about the different features and techniques.",
                    },
                    items: [{ type: "autogenerated", dirName: "tutorials" }],
                },
                { type: "link", label: "Data Rest API", href: "/docs/category/data-rest-api-v1" },
            ],
        },
    ],
    "restApi-1.0": [
        {
            type: "html",
            defaultStyle: true,
            value: versionSelector(restApiVersions),
            className: "version-button",
        },
        {
            type: "html",
            defaultStyle: true,
            value: versionCrumb(`V1`), // The version label you wish to display
        },
        {
            type: "category",
            label: "Data Rest API",
            link: {
                type: "generated-index",
                title: "Data Rest API - V1",
                description: "Novorender Data REST API Docs",
                slug: "/category/data-rest-api-v1",
            },
            items: require("./docs/rest-api/sidebar.js"),
        },
    ],
    "restApi-2.0": [
        {
            type: "html",
            defaultStyle: true,
            value: versionSelector(restApiVersions),
            className: "version-button",
        },
        {
            type: "html",
            defaultStyle: true,
            value: versionCrumb(`V2`), // The version label you wish to display
        },
        {
            type: "category",
            label: "Data Rest API",
            link: {
                type: "generated-index",
                title: "Data Rest API - V2",
                description: "Novorender Data REST API Docs",
                slug: "/category/data-rest-api-v2",
            },
            items: require("./docs/rest-api/2.0/sidebar.js"),
        },
    ],
};

module.exports = sidebars;
