import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import dataRestApiV2Sidebar from "./docs/data_rest_api_v2/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Web API",
      link: {
        type: "doc",
        id: "web_api/index",
        // description: "Learn more about the Novorender's open source APIs",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Tutorial",
          link: {
            type: "doc",
            id: 'web_api/tutorial/getting_started',
          },
          items: [{
            type: 'doc',
            id: 'web_api/tutorial/getting_started',
          }],
        },
        {
          type: "category",
          label: "API Reference",
          link: {
            type: "doc",
            id: "web_api/api_reference/index",
          },
          items: [require('./docs/web_api/api_reference/typedoc-sidebar.cjs')],
        }
      ],
    },
    {
      type: "category",
      label: "Data JS API",
      link: {
        type: "doc",
        id: "data_js_api/api_reference/index",
      },
      items: [
        {
          type: "category",
          label: "API Reference",
          link: {
            type: "doc",
            id: "data_js_api/api_reference/index",
          },
          items: [require('./docs/data_js_api/api_reference/typedoc-sidebar.cjs')],
        }
      ],
    },
    { type: "link", label: "Data Rest API", href: "/docs/category/data_rest_api_v2" },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
        description: "Learn more about the different features and techniques.",
      },
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
  ],
  dataRestApiV2Sidebar: [
    {
      type: "category",
      label: "Data Rest API",
      link: {
        type: "generated-index",
        title: "Data Rest API V2",
        description: "The Novorender REST API allows you to interact with your 3D models uploaded to Novorender.",
        slug: "/category/data_rest_api_v2",
      },
      items: dataRestApiV2Sidebar,
    }
  ]
};

export default sidebars;
