const fs = require("fs");

const source = fs.readFileSync("node_modules/@novorender/api/index.js", { encoding: "utf-8" });
const match = /export {\n([^}]*)};/g.exec(source);
const _exports = match[1];
const trimmed = _exports.replace(/\w+ as /g, "");
const proxyCode = `/** THIS IS AN AUTOGENERATED FILE VIA "scripts/extract-exports.js" - DO NOT MODIFY THIS FILE MANUALLY */\nexport const {\n${trimmed}} = window["__novorender__"];`;
fs.writeFileSync("static/api_proxy.js", proxyCode);
